v0.6.0 - Better compiled language support - Add better repository name extraction - Add suite support - Fix upload last SARIF bug - Add SARIF snippets by default - Set CodeQL to use all threads on host

diff --git a/gh-codeql-scan b/gh-codeql-scan
--- a/gh-codeql-scan
+++ b/gh-codeql-scan
@@ -1,11 +1,12 @@
 #!/bin/bash
 set -eu
+
 export EXTENSION_LOCATION="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
 
 source $EXTENSION_LOCATION/bin/codeql-utils
 
 # >> CodeQL Scan
-export CODEQL_SCAN_VERSION="0.5.0"
+export CODEQL_SCAN_VERSION="0.5.1"
 # enabled by default
 export CODEQL_SCAN_BANNER=1
 
@@ -16,9 +17,9 @@ export CODEQL_DATABASES_OVERRIDE=1
 export CODEQL_RESULTS="${CODEQL_RESULTS:=$HOME/.codeql/results}"
 export CODEQL_BINARY="${CODEQL_BINARY:=gh codeql}"
 # `code-scanning` (default), `security-extended`, or `security-and-quality`
-export CODEQL_SUITE="${CODEQL_SUITE:=code-scanning}"
+export CODEQL_SUITE="${CODEQL_SUITE:=}"
 # Tracing is disabled by default
-export CODEQL_TRACING=1
+export CODEQL_TRACING=0
 export CODEQL_LANGUAGES=
 # this variable is used to know while databases need to be analyzed
 export CODEQL_DATABASE_PATHS_FILE="${CODEQL_DATABASE_PATHS_FILE:=/tmp/codeql-database-paths.txt}"
@@ -85,11 +86,15 @@ for i in "$@"; do
         ;;
     -c=*|--command=*)
         export CODEQL_BUILD_COMMAND="${i#*=}"
-        export CODEQL_TRACING=0    # disable tracing too
+        export CODEQL_TRACING="1"    # enable tracing
         shift
         ;;
     -d=*|--databases=*)
         export CODEQL_DATABASES="${i#*=}"
+        shift
+        ;;
+    -s=*|--suite=*)
+        export CODEQL_SUITE="${i#*=}"
         shift
         ;;
     -b=*|--binary=*|--codeql-bin=*)
@@ -146,12 +151,19 @@ fi
 # Auto detect the repository owner and name
 if [ -z ${GITHUB_REPOSITORY+x} ]; then
     REMOTE=$(git config --get remote.origin.url)
-    # TODO: support for ssh remotes
-    export GITHUB_REPOSITORY=$(echo $REMOTE | sed -e 's/.*github.com[:\/]\(.*\)\.git/\1/')
-
-    info "Using remote repository: $GITHUB_REPOSITORY"
+    if [[ $REMOTE == git@* ]]; then
+        debug "Using SSH remote :: $REMOTE"
+        # only works for github.com repositories
+        export GITHUB_REPOSITORY=$(echo $REMOTE | sed -e 's/.*github.com[:\/]\(.*\)\.git/\1/')
+    elif [[ $REMOTE == https://* ]]; then
+        debug "Using HTTPS remote :: $REMOTE"
+        export GITHUB_REPOSITORY=${REMOTE#*://*/} && export GITHUB_REPOSITORY=${GITHUB_REPOSITORY%.git}
+    else
+        error "Unable to auto-detect the repository owner and name"
+        exit 1
+    fi
+    info "Using remote repository :: $GITHUB_REPOSITORY"
 fi
-
 
 # Running different modes
 if [ $MODE = "init" ]; then
@@ -173,9 +185,6 @@ elif [ $MODE = "upload" ]; then
 
 elif [ $MODE = "scan" ]; then
     info "Running Scan mode..."
-
-    debug "Disable build tracing as it can not be used in this mode"
-    export CODEQL_TRACING=0
 
     $EXTENSION_LOCATION/bin/codeql-init $@
 
